[package]
name = "brain-games"
description = "Brain games on Rust"
version = "1.0.0"
edition = "2021"
keywords = ["games", "study"]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rand = "0.8.5"

[profile.release]
strip = true